-- CREATE TABLE items (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   itemName VARCHAR(255) NOT NULL,
--   itemPrice DECIMAL(10, 2) NOT NULL
-- );

CREATE TABLE items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  itemName VARCHAR(255) NOT NULL,
  itemPrice DECIMAL(10, 2) NOT NULL,
  itemImage VARCHAR(255)
);

CREATE TABLE cart_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  itemName VARCHAR(255) NOT NULL,
  itemPrice DECIMAL(10, 2) NOT NULL,
  quantity INT NOT NULL DEFAULT 0
);

CREATE TABLE orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  billItems TEXT NOT NULL,
  total DECIMAL(10, 2) NOT NULL,
  date DATETIME NOT NULL
);
